name: vac
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - ipykernel
  - pip:
      - advertorch==0.2.3
      - matplotlib==3.9.4
      - numpy==1.24.4
      - opencv-python==4.11.0.86
      - pillow==11.1.0
      - robustbench==1.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - timm==0.4.12
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchdiffeq==0.2.5
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - wandb==0.19.8