dataset: 'cifar10'
net_type: 'preactresnet18'
model_width: 64
data_dir: 'data'
corrupted_data_dir: 'data/CIFAR-10-C'

batch_size: 128
lr: 0.1
print_freq: 200
weight_decay: 0.0005

sigmas: [0]
epochs: [200]

expname: 'runs/cifar10/preactresnet18/vanilla'


